### ISSUE TITLE
Error on accessing the $phpMussel const

### ISSUE THREAD

**Issue by segpacto** [mtrefzer/plugin-resultAsJson#2]
The plugin is properly initialized, however when I load a regular page of my web it loads blank,
on the php error.log I get this message 
"FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Function name must be a string in /usr/local/src/phpMussel/vault/plugins/resultAsJson/plugin.php:41
Stack trace:
#0 /usr/local/src/phpMussel/phpmussel.php(174): require_once()
#1 {main}
  thrown in /usr/local/src/phpMussel/vault/plugins/resultAsJson/plugin.php on line 41" while reading response header from upstream, client: xxx.xxx.xx.xx, server: demo.flexperto.dev, request: "GET /dash/xxx HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxx.xxxxx.xxx"
" 

I been debugging and trying to access $phpMussel['Register_Hook'] and is null.
What could be happening ?

**Comment by mtrefzer** [comment]
May be this was caused by some changes in the plugin system. 

Checkout the actual sources of phpmussel and this plugin and try it again.

**Comment by Maikuolan** [comment]
I don't think the plugin is at fault here; There's nothing in the plugin code AFAIK that could cause an error message like that. Although I haven't seen this happen before during local testing for the main package, any of the plugins and etc, considering that I recently made some changes to the plugin system in the main phpMussel package, I'd wager that it's more likely to be something there at fault than anything else.

I'll do some more testing on my end later tonight to see whether I can get to the bottom of this, whether I can replicate the problem and so on.

Also, if possible, could you let us know which version of PHP you're using, and whether you're using the latest version of the main package or something else? Just in case that has anything to do with it. Cheers.

**Comment by Maikuolan** [comment]
I think I might've figured out what's going on.

Judging by the main loader path cited in the stack trace (`/usr/local/src/phpMussel/phpmussel.php`), I'm guessing you're running phpMussel v0.10.0? Technically, v0.10.0 would be the "latest version" in the sense that it is the latest release, but the plugin requires phpMussel v1.0.0-DEV or newer to function correctly (the current master codebase cites v1.0.0-DEV; we're currently preparing to release the next version of phpMussel, v1.0.0, relatively soon, and v1.0.0 won't be backwards-compatible with previous versions of phpMussel, so there may be some strange and unexpected errors appearing at times when using v1.x.x plugins with v0.x.x package releases).

**Comment by segpacto** [comment]
Yes, @Maikuolan 
it seems that there are several mismatches between the versions used by the plugin and the latest version,
also on the documentation of the plugin because is referring to 'phpmussel.ini' however on master of phpMussel is using as configuration 'config.ini'.

Thanks for the help, I guess I will be waiting for v1.0.0

**Comment by Maikuolan** [comment]
@segpacto phpMussel v1.0.0 has just been released today. :-)

**Comment by segpacto** [comment]
Thanks for the update @Maikuolan
